### ISSUE TITLE
Pre-training error

### ISSUE THREAD

**Issue by cozymichelle** [Tribleave/SCAPT-ABSA#9]
Hello,
I get the following CUDA error when I run the pre-training code:
```
CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```
I installed requirements, downloaded the data, and followed the pre-training instruction.
Is there a way I could fix this error?
And is there a way I could run the pre-training code in CPU, not GPU?

**Comment by Tribleave** [comment]
Hi, I have googled this bug and the most the workaround is about the PyTorch version. I think you have just checked it. So I also have no idea.

The code is written specifically for GPU because we use multiple-GPUs and half precision. Thus there is no CPU version provided. Maybe you can convert the code to CPU version and this may be really helpful for the others! (However that can be relatively slow.)

**Comment by cozymichelle** [comment]
Thank you for the comment.
I originally installed PyTorch 1.18.0, as written in your instruction. But upgrading to 1.19 solved the problem. Thanks.
